# Generated by Django 3.1 on 2020-08-30 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200824_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='askFrom',
            new_name='ask_from',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='askTo',
            new_name='ask_to',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nickName',
            new_name='nick_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userPro',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('ask_from', 'ask_to')},
        ),
    ]
