# Generated by Django 3.1 on 2020-08-30 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200830_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='ask_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='ask_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
